// <auto-generated />
using System;
using Mercadados_API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mercadados_API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251128133444_Ctmercadadosazure")]
    partial class Ctmercadadosazure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mercadados_API.Domains.Estoque", b =>
                {
                    b.Property<Guid>("EstoqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.HasKey("EstoqueID");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("Mercadados_API.Domains.EstoqueProdutos", b =>
                {
                    b.Property<Guid>("EstoqueProdutosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EstoqueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutosID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("Int");

                    b.HasKey("EstoqueProdutosID");

                    b.HasIndex("EstoqueID");

                    b.HasIndex("ProdutosID");

                    b.ToTable("EstoqueProdutos");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFeedback")
                        .HasColumnType("DATETIME");

                    b.Property<Guid>("FuncionarioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.HasKey("FeedbackID");

                    b.HasIndex("FuncionarioID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Funcionario", b =>
                {
                    b.Property<Guid>("FuncionarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CidadeEstadoCEP")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Complemento")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("VARCHAR(13)");

                    b.Property<string>("RuaENumero")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FuncionarioID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.TipoUsuario", b =>
                {
                    b.Property<Guid>("TipoUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TituloTipoUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("TipoUsuarioID");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("VARCHAR(13)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("TipoUsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioID");

                    b.HasIndex("TipoUsuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Mercadados_API.Models.Imagem", b =>
                {
                    b.Property<Guid>("ImagemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ImagemID");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("Produtos", b =>
                {
                    b.Property<Guid>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("VARCHAR(250)");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("Varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<int>("NumeroProduto")
                        .HasColumnType("INT");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("Varchar(250)");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("DATE");

                    b.Property<double>("Valor")
                        .HasColumnType("Float");

                    b.HasKey("ProdutoID");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Venda", b =>
                {
                    b.Property<Guid>("VendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FeedbackID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProdutosProdutoID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT");

                    b.Property<double>("Valor")
                        .HasColumnType("FLOAT");

                    b.HasKey("VendaID");

                    b.HasIndex("FeedbackID");

                    b.HasIndex("ProdutosProdutoID");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Mercadados_API.Domains.EstoqueProdutos", b =>
                {
                    b.HasOne("Mercadados_API.Domains.Estoque", "Estoque")
                        .WithMany()
                        .HasForeignKey("EstoqueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Produtos", "Produtos")
                        .WithMany()
                        .HasForeignKey("ProdutosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Feedback", b =>
                {
                    b.HasOne("Mercadados_API.Domains.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Funcionario", b =>
                {
                    b.HasOne("Mercadados_API.Domains.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Usuario", b =>
                {
                    b.HasOne("Mercadados_API.Domains.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Venda", b =>
                {
                    b.HasOne("Mercadados_API.Domains.Feedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackID");

                    b.HasOne("Produtos", "Produtos")
                        .WithMany()
                        .HasForeignKey("ProdutosProdutoID");

                    b.Navigation("Feedback");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
